### ISSUE TITLE
Validation so a tab can only be used inside of a tabset

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-elemental-tabset#4]

**Comment by imantzios-wigital** [comment]
You can achieve this by doing something like this in your yml

```
Page:
  disallowed_elements:
    - Dynamic\Elements\Tabset\Element\TabElement #TabElement not allowed anywhere
Dynamic\Elements\Tabset\Element\ElementTabSet:
  allowed_elements:
    - Dynamic\Elements\Tabset\Element\TabElement #tabset allows TabElement
```
